namespace Sandbox.Classes.Cards.CardFrames;

public enum FrameEffect
{
	Legendary = 0,
	Miracle = 1,
	Enchantment = 2,
	Draft = 3,
	Devoid = 4,
	Tombstone = 5,
	Colorshifted = 6,
	Inverted = 7,
	SunMoonDfc = 8,
	CompassLandDfc = 9,
	OriginPwDfc = 10,
	MoonEldraziDfc = 11,
	WaxingAndWaningMoonDfc = 12,
	Showcase = 13,
	ExtendedArt = 14,
	Companion = 15,
	Etched = 16,
	Snow = 17,
	Lesson = 18,
	ShatteredGlass = 19,
	ConvertDfc = 20,
	FanDfc = 21,
	UpsideDownDfc = 22,
	Spree = 23,
	Fullart = 24,
}
